"""Constants for the CPT integration."""
DOMAIN = "cpt"
COMBUSTION_MANUFACTURER_ID = 2503
COMBUSTION_INC = "Combustion Inc."


CONF_INCLUDE_VIRTUAL_SENSORS = "enable_virtual_sensors"
CONF_INCLUDE_PHYSICAL_SENSORS = "enable_physical_sensors"

PROBE_STATUS_CHARACTERISTIC = "00000101-CAAB-3792-3D44-97AE51C1407A"

BATTERY_STATE_OK = "OK"
BATTERY_STATE_LOW = "LOW"
BATTERY_STATE_UNKNOWN = "Unknown"
