"""Constants for the CPT integration."""
DOMAIN = "cpt"
COMBUSTION_MANUFACTURER_ID = 2503
COMBUSTION_INC = "Combustion Inc."


CONF_INCLUDE_VIRTUAL_SENSORS = "include_virtual_sensors"
CONF_INCLUDE_PHYSICAL_SENSORS = "include_physical_sensors"

PROBE_STATUS_CHARACTERISTIC = "00000101-CAAB-3792-3D44-97AE51C1407A"
