"""Constants for the CPT integration."""
DOMAIN = "cpt"
COMBUSTION_MANUFACTURER_ID = 2503
COMBUSTION_INC = "Combustion Inc."


CONF_INCLUDE_VIRTUAL_SENSORS = "enable_virtual_sensors"
CONF_INCLUDE_PHYSICAL_SENSORS = "enable_physical_sensors"

PROBE_STATUS_CHARACTERISTIC = "00000101-CAAB-3792-3D44-97AE51C1407A"

BATTERY_STATE_OK = "OK"
BATTERY_STATE_LOW = "Low"
BATTERY_STATE_UNKNOWN = "Unknown"


PREDICTION_STATE_PREDICTING = "Prediction Available"
PREDICTION_STATE_NOT_INSERTED = "Probe Not Inserted"
PREDICTION_STATE_PENDING = "Calculating Prediction"
PREDICTION_STATE_INSERTED = "Probe Inserted"
PREDICTION_STATE_READY = "Food is Ready!"
PREDICTION_STATE_NOT_PREDICTING = "Not Predicting"
PREDICTION_STATE_OTHER = "Unknown"
